### ISSUE TITLE
Animation not starting at first time

### ISSUE THREAD

**Issue by Miteshmakwana73** [jackpocket/android-pulse-indicator#4] opened 2020-11-18 06:33 UTC
i have a fragment when start animation it's not starting first time but if i try after some time it is working don't know what is wrong please help me

**it only start if i click on button it's not starting if i call this function in on create** 

**XML**

```
<com.jackpocket.pulse.layouts.PulsingLinearLayout
                android:id="@+id/lnScanning"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:gravity="center"
                android:orientation="vertical"
                android:visibility="@{isScanning ? View.VISIBLE: View.GONE}">

                <ImageView
                    android:id="@+id/imgAnim"
                    android:layout_width="@dimen/_90sdp"
                    android:layout_height="@dimen/_90sdp"
                    android:padding="@dimen/_20sdp"
                    android:src="@drawable/ic_search"
                    android:background="@drawable/circle" />

                <TextView
                    style="@style/fontBold"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="@dimen/_95sdp"
                    android:text="scanning"
                    android:textColor="@color/black"
                    android:textSize="@dimen/_14ssp" />

            </com.jackpocket.pulse.layouts.PulsingLinearLayout>
```

**Kotlin**
```
fun startAnim() {
        MyLog.d(TAG, "Pulse Started.")
        binding.lnScanning.pulseController
            .setCirclePathOverride(true)
            .setPulsingColor(0x00afca)
            .setPulsingStrokeWidth(5)
            .setDurationMs(TimeUnit.DAYS.toMillis(1))
            .setPulseLifeSpanMs(900)
            .setRespawnRateMs(300)
            .setAlphaInterpolator(AccelerateInterpolator())
            .setScaleInterpolator(LinearInterpolator())
            .setFinishedListener({ _ ->
                MyLog.d(TAG, "Pulse completed.")
            })
            .attachTo(activity, binding.imgAnim)
    }
```

i am calling this function on createview

**Comment by mattsilber** [comment] 2020-11-18 14:37
Hello, after a little digging, I think it _is_ actually starting, but might be attaching itself to wherever `View.getWindowLocation(int[])` returns when the View is not actually attached to the Window... which also explains why it works when you delay it until after the View has actually been presented.

The window coordinates of the target View [are collected](https://github.com/jackpocket/android-pulse-indicator/blob/e5942777676053d5b7b6ff0da6366cc35c50cae4/pulse-indicator/src/main/java/com/jackpocket/pulse/PulseController.java#L142) during the `attachTo` flow in order to determine the `PulseController.pulseStartBoundaries`.

The solution for now would be to defer the `attachTo` call until the View is actually attached to the window. [This StackOverflow post](https://stackoverflow.com/a/63591019/1426565) on overriding `setMenuVisibility` should point you in the right direction

**Comment by Miteshmakwana73** [comment] 2020-11-19 04:40
@mattsilber setMenuVisibility is not working for me

```
override fun setMenuVisibility(menuVisible: Boolean) {
        super.setMenuVisibility(menuVisible)
        onTestPulseClicked()
    }
```


 it's also not working if I call this function on `onViewCreated` i think all the view are must be attached to `onViewCreated` 

facing the same problem in activity also not starting animation if I call a function in onCreate it's only starting on button click

I tested in all possible scenario and it's only working on button click can you please check and update

**Comment by mattsilber** [comment] 2020-11-19 14:25
Unfortunately, using `onViewCreated` will have the same issue as using `onCreateView`. From the [Fragment#onViewCreated docs](https://developer.android.com/reference/android/app/Fragment#onViewCreated(android.view.View,%20android.os.Bundle)):

> The fragment's view hierarchy is not however attached to its parent at this point.

The problem is, you're attempting to start the `PulseController` _before_ your View is actually attached to the window for this particular case.

> facing the same problem in activity also not starting animation if I call a function in onCreate it's only starting on button click

It's the [same problem](https://stackoverflow.com/q/13243914/1426565) where `Activity#onCreate` is too early to start the `PulseController` because it cannot yet find the location to start the pulses from.

In the Activity case, the `attachTo` call should be deferred until a better point, like `Activity#onResume`. 

Since it looks like you're also attempting to perform an indefinite pulse, you'll want to make sure you're calling `PulseController#suspendPulseCreation` in the equivalent closing lifecycle method (`Activity#onPause`) so that the task can die gracefully.

**Comment by Miteshmakwana73** [comment] 2020-11-19 14:38
@mattsilber I don't understand so how can I perform this animation on fragment start because the below code is not working for me

> override fun setMenuVisibility(menuVisible: Boolean) {
        super.setMenuVisibility(menuVisible)
        onTestPulseClicked()
    }

is there any ex available of this library which starts the animation when fragment created or any suggestion 


Please help me because this is a very useful library with smooth animation and I want to implement this

**Comment by mattsilber** [comment] 2020-11-19 15:13
Is there any reason you can't use [Fragment#onStart](https://developer.android.com/reference/android/app/Fragment.html#onStart%28%29)?

Otherwise, you might find some information [in this post](https://stackoverflow.com/questions/18375288/fragment-lifecycle-which-method-is-called-upon-show-hide)

**Comment by Miteshmakwana73** [comment] 2020-11-19 16:47
@mattsilber  are you saying i have to call `onTestPulseClicked()` function in `onStart` of fragment?

**Comment by Miteshmakwana73** [comment] 2020-11-20 05:04
because `onStart` is also not working for me

```
override fun onStart() {
        super.onStart()
        onTestPulseClicked()
    }
```

**Comment by Miteshmakwana73** [comment] 2020-11-20 05:39
@mattsilber I got the solution by using post kotlin (**don't know it will work same on JAVA**)

```
main__action_pulse.post {
            onTestPulseClicked()
        }
```
**OR**
```
getView()?.post {
            onTestPulseClicked()
        }
```

i implemented like this

```
fun startAnim() {
        MyLog.d(TAG, "Pulse Started.")
        binding.lnScanning.post {
            binding.lnScanning.pulseController
                .setCirclePathOverride(true)
                .setPulsingColor(0x00afca)
                .setPulsingStrokeWidth(5)
                .setDurationMs(TimeUnit.DAYS.toMillis(1))
                .setPulseLifeSpanMs(900)
                .setRespawnRateMs(300)
                .setAlphaInterpolator(AccelerateInterpolator())
                .setScaleInterpolator(LinearInterpolator())
                .setFinishedListener({ _ ->
                    MyLog.d(TAG, "Pulse completed.")
                })
                .attachTo(activity, binding.imgAnim)
        }
    }
```

> **you can add this on your document or code so other people can easily understand**

or add functionality which works in all scenario

**Closed as completed** 2021-09-17 17:57 UTC

**Comment by mattsilber** [comment] 2021-09-17 18:01
In version 2.0.0, you should be able to drop the `View.post` calls by replacing the method `attachTo` with `attachToOnUiThread`. 

Note: if you're using the finished-callback (`setFinishedListener`), make sure to replace it with a strong reference as the underlying `PulseEventListener` was changed in 2.0.0 to be weakly held.
